name = "school-formula-api"
main = "worker/index.ts"
compatibility_date = "2026-09-06"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "api.syy.global/*", zone_name = "syy.global" },
  { pattern = "api.syy.mobi/*", zone_name = "syy.mobi" },
  { pattern = "api.syy.one/*", zone_name = "syy.one" }
]

[[d1_databases]]
binding = "DB"
database_name = "school-formula-db"
database_id = "21a53ef9-a1ea-434d-9c18-f3619421f011"

[[kv_namespaces]]
binding = "SESSIONS"
id = "e7c94f92016f4458863363fb666b5b33"

[site]
bucket = "./dist"

[vars]
FRONTEND_URL = "https://syy.global"
FROM_EMAIL = "noreply@syy.global"
ALLOWED_ORIGINS = "https://syy.global,https://syy.mobi,https://syy.one"
ENVIRONMENT = "production"
