#!/usr/bin/env tsx
import 'dotenv/config';
import OpenAI from 'openai';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { buildPrompt } from './prompts';
import { loadKnowledgePoints } from './knowledge-loader';
import type { QuestionType, Difficulty, GradeLevel } from '../../src/data/questions/types';

const QUESTION_TYPES: QuestionType[] = ['choice', 'fill-blank', 'true-false'];
const DIFFICULTIES: Difficulty[] = ['basic', 'intermediate', 'advanced'];

function parseArgs() {
  const args = process.argv.slice(2);
  return {
    all: args.includes('--all'),
    grade: args.find(a => a.startsWith('--grade='))?.split('=')[1] as GradeLevel | undefined,
    subject: args.find(a => a.startsWith('--subject='))?.split('=')[1],
    incremental: args.includes('--incremental'),
  };
}

async function generateQuestion(
  client: OpenAI,
  model: string,
  kp: { id: string; title: string; description: string; tags: string[]; subject: string; grade: GradeLevel },
  type: QuestionType,
  difficulty: Difficulty,
): Promise<object | null> {
  const prompt = buildPrompt(kp.title, kp.description, kp.tags, kp.subject, kp.grade, type, difficulty);

  try {
    const response = await client.chat.completions.create({
      model,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.8,
    });

    const content = response.choices[0]?.message?.content || '';
    const jsonMatch = content.match(/```json\s*([\s\S]*?)\s*```/) || content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error(`  ❌ Failed to parse JSON for ${kp.title} ${type} ${difficulty}`);
      return null;
    }

    const parsed = JSON.parse(jsonMatch[1] || jsonMatch[0]);
    return {
      id: `q-${kp.subject}-${kp.grade}-${kp.id}-${difficulty}-${type}`,
      type,
      difficulty,
      knowledgePointIds: [kp.id],
      subject: kp.subject,
      grade: kp.grade,
      tags: kp.tags,
      ...parsed,
    };
  } catch (error) {
    console.error(`  ❌ Error generating for ${kp.title}:`, error);
    return null;
  }
}

async function main() {
  const { grade, subject } = parseArgs();

  if (!process.env.OPENAI_API_KEY) {
    console.error('Error: OPENAI_API_KEY not set in environment');
    process.exit(1);
  }

  const client = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
    baseURL: process.env.OPENAI_BASE_URL,
  });

  const model = process.env.OPENAI_MODEL || 'gpt-4o';

  const kps = loadKnowledgePoints(grade, subject);
  console.log(`Found ${kps.length} knowledge points`);

  const results: Record<string, object[]> = {};

  for (const kp of kps) {
    console.log(`\n📝 Generating for: ${kp.title} (${kp.subject} ${kp.grade})`);
    const questions: object[] = [];

    for (const type of QUESTION_TYPES) {
      for (const difficulty of DIFFICULTIES) {
        console.log(`  - ${type} ${difficulty}...`);
        const q = await generateQuestion(client, model, kp, type, difficulty);
        if (q) questions.push(q);
      }
    }

    results[kp.id] = questions;
    console.log(`  ✅ Generated ${questions.length} questions`);
  }

  const outputDir = join(__dirname, '../../src/data/questions');
  mkdirSync(outputDir, { recursive: true });

  const outputPath = join(outputDir, 'generated.ts');
  const outputContent = `// Auto-generated by scripts/generate-questions/generate.ts
// Do not edit manually
import type { Question } from './types';

export const generatedQuestions: Question[] = ${JSON.stringify(
    Object.values(results).flat(),
    null,
    2
  ).replace(/"(\w+)":/g, '$1:')};
`;

  writeFileSync(outputPath, outputContent);
  console.log(`\n✅ Done! Generated ${Object.values(results).flat().length} questions total`);
  console.log(`📄 Output: ${outputPath}`);
}

main().catch(console.error);
